version: '3.9'
services:
  cloudflared:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    ports:
          - target: 5053
            published: 5053
            protocol: udp
          - target: 49312
            published: 49312
            protocol: tcp
    environment:
      # - TUNNEL_TOKEN=mytokengoeshere
      - "TZ=Europe/Paris"
      - "TUNNEL_DNS_UPSTREAM=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query"
    restart: always

